// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

// pref(key,value) 会覆盖默认设置,在删除之后会恢复默认设置。
// user_pref(key,value) 等同于从about:config修改,删除之后,修改的设置仍然有效。

// 关闭标签动画（老机器可以设置为false，高配电脑无需设置）
user_pref("toolkit.cosmeticAnimations.enabled", false);

// 设置标签页面缓存的数量，默认为-1，意为无限大。
user_pref("browser.sessionhistory.max_total_viewers", 16);

// 设置链接是否在新窗口中打开： 默认为3，3表示在新标签页中打开，2表示在新窗口中打开，1表示在当前窗口或者标签页中打开。
user_pref("browser.link.open_newwindow", 3);

// 关闭最后一个标签页时不关闭 Firefox
user_pref("browser.tabs.closeWindowWithLastTab", false);

// 更改标签页最小宽度
user_pref("browser.tabs.tabMinWidth", 100);
